# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /default_images/page_background.jpg
post_background: /default_images/post_background.jpg
title_plancehold: 随笔
author:
  head: /default_images/author_head.gif
  signature: talk is cheap,show me the code
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr]
social:
  - name: GitHub
    icon: github
    link: http://github.com/Professor-Z
  - name: Weibo
    icon: weibo
    link: http://weibo.com/vuuihc
# Duoshuo
duoshuo:
  enable: true
  siteName: vuuihc
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true
